name: build-release

on:
  push:
    tags:
      - "v*.*.*"

permissions: read-all

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-site:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.0

      - name: Install dependencies
        run: |
          opam option --global 'archive-mirrors+="https://opam.ocaml.org/cache"'
          opam install . --deps-only
          opam exec -- dune build --profile=release


      - name: build package
        run: |
          bash scripts/mkrel.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: sb

